# Generated by Django 4.0.5 on 2022-06-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitchapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertrip',
            name='path_points',
            field=models.TextField(null=True),
        ),
    ]
