# Generated by Django 4.0.5 on 2022-06-13 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hitchapi', '0002_drivertrip_path_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.FloatField(null=True)),
                ('lat', models.TextField()),
                ('lng', models.TextField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hitchapi.drivertrip')),
            ],
        ),
    ]
