# Generated by Django 4.0.5 on 2022-06-13 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hitchapi', '0003_pathpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivertrip',
            name='path_points',
        ),
        migrations.DeleteModel(
            name='PathPoint',
        ),
    ]
