# Generated by Django 4.0.5 on 2022-06-14 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hitchapi', '0004_remove_drivertrip_path_points_delete_pathpoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivertrip',
            old_name='drop_off_radius',
            new_name='detour_radius',
        ),
        migrations.RemoveField(
            model_name='drivertrip',
            name='pick_up_radius',
        ),
    ]
