# Generated by Django 4.0.5 on 2022-06-17 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hitchapi', '0005_rename_drop_off_radius_drivertrip_detour_radius_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverTripRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('driver_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hitchapi.drivertrip')),
            ],
        ),
    ]
