# Generated by Django 4.0.5 on 2022-06-17 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hitchapi', '0006_drivertriprating'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertriprating',
            name='passenger_trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hitchapi.passengertrip'),
            preserve_default=False,
        ),
    ]
